### ISSUE TITLE
check_multi sees 2 processes while the plugin only sees 1

### ISSUE THREAD

**Issue by klonski** [flackem/check_multi#1]
the check:
./check_multi -f /etc/appl_procs.cfg -n appl_procs -r 32769

appl_procs OK - 1 plugins checked, 1 ok
[ 1] check_weblogic PROCS OK: 2 processes with args '/jrockit_150_11/bin/java -jrockit'

the config line :
command[ check_weblogic ]        = /opt/nagios/libexec/check_procs -t 120 -c 1: -a '/jrockit_150_11/bin/java -jrockit'

if I run the the plugin alone I get :
PROCS OK: 1 process with args '/jrockit_150_11/bin/java -jrockit'

there is only 1 process, but check_multi reports 2 processes
system is a 32 bit RHEL 5.4 2.6.9-89.ELsmp
check_multi version 0.23
perl  v5.8.5

**Comment by flackem** [comment]
Hi,

your check_procs call lacks a command, specified with -C <command>.

When you only add a -a <argument> clause, the whole process list will be searched for the argument string, and also catches the check_multi forked instances to execute the plugin.

Example with init:
Wrong call without -C brings 3 results
[nagios] $ check_multi -x 'command [ init ] = check_procs -c 1: -a init' -r 1
OK - 1 plugins checked, 1 ok
[ 1] init PROCS OK: 3 processes with args 'init'

Correct call with -C brings 1 result
[nagios] $ check_multi -x 'command [ init ] = check_procs -c 1: -C init -a init' -r 1
OK - 1 plugins checked, 1 ok
[ 1] init PROCS OK: 1 process with command name 'init', args 'init'

Cheers,
-Matthias

**Comment by klonski** [comment]
Ahh I see, got it, thanks
