### ISSUE TITLE
buggy permission check

### ISSUE THREAD

**Issue by glensc** [flackem/check_multi#6]
there's some code in it which checks for directory permission, and if it's incorrect, it will attempt to fix it.

the check however is broken, so that attempts to fix it every time

```
$ install -d -m 770 test
$ ls -lad test
drwxrwx--- 2 nagios nagios 6 juuni 25 22:35 test/
$ perl -e 'printf("%o\n", (stat("test"))[2])'
40770
```

because if you read the manual, then offset 2 aka mode contains TYPE and PERMISSIONS:

```
             2 mode     file mode  (type and permissions)
```

and includes sample how to check only permissions:

```
           Because the mode contains both the file type and its permissions, you should mask off the file type
           portion and (s)printf using a "%o" if you want to see the real permissions.

               $mode = (stat($filename))[2];
               printf "Permissions are %04o\n", $mode & 07777;
```

i.e in my sample:

```
$ perl -e 'printf("%o\n", (stat("test"))[2] & 07777)'
770
```

**Comment by glensc** [comment]
patch to fix: http://cvs.pld-linux.org/packages/nagios-plugin-check_multi/issue-6.patch

**Comment by flackem** [comment]
Hi Elan,

thanks for your good eye and the patch.

Cheers,
-Matthias
